### ISSUE TITLE
Collection: Reading element with [] returns undecorated element

### ISSUE THREAD

**Issue by mswiszcz** [fnando/burgundy#5]
Hello,

I've one problem with burgundy collection decorator. When I decorate collection of elements with

``` ruby
@job_titles = JobTitlePresenter.wrap(job_titles)
```

and try to read element with [] operator it returns undecorated element

``` ruby
irb(main):063:0> @job_titles[0].attributes
=> {"id"=>1, "hidden"=>false, "key_facts"=>nil, "count_sum"=>601} # only job_title attributes, undecorated
irb(main):064:0> @job_titles.first.attributes
=> {:id=>1, :name=>"Gärtner", :teaser=>"<p..." # presenter attributes
```

This makes impossible to get last elements of array using `[5..-1]` (which I am using in view) or using `.last` methods

The workaround I've found for this is to use .to_ary before trying to read elements with [] or .last, but it would be great if we could ommit this method

**Comment by fnando** [comment]
First of all, sorry about taking 2+ years to answer this: that sucks big time (I've disabled Github notifications a long time ago).

You're right, fetching items from `Burgundy::Collection` should always wrap items with the decorator class. The problem is that the surface area is way too big; what about other methods like `Array#slice`, `Array#fetch`, and all the other methods that `Array` implements? I think we should implement only `Array#[](index)` and add a note on readme about this behavior.

**Comment by fnando** [comment]
2cea9b5cfc82507f15566dfa2e93bc0c7da39cc2 replaces `SimpleDelegator` with `method_missing` calling through the wrapped collection. This will make sure that any operations on the array will return wrapped items.

**Comment by fnando** [comment]
v0.3.0 released.
